@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/63283a8fb4765adad51dad58
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/63283a8fb4765adad51dad58/6323fed45e312bf197646a27
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/63283a8fb4765adad51dad58
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/block/63283a8fb4765adad51dad59
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/63283a8fb4765adad51dad58
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
